### ISSUE TITLE
Export HL7 versions

### ISSUE THREAD

**Issue by glenarama** [Bugs5382/node-hl7-client#81]
Need to be able to create versions other than 2.7 

Currently the example shows creation using:

`specification: new HL7_2_3()`

However the HL7 versions are not exported, so 2.7 is used by default. This then forces 9 to have a secondary constructed ADT message which breaks the 2.2 server im trying to communicate with.

Could HL7_2* be exported or added as a messageHeader option?

**Comment by Bugs5382** [comment]
Yep. I already know about this... I have yet to get around to it.

**Comment by Bugs5382** [comment]
Got it working..

![image](https://github.com/Bugs5382/node-hl7-client/assets/12115015/068cd00f-6453-4c72-b817-54e701c15c95)

Release coming very shortly.

**Comment by Bugs5382** [comment]
Can you try:

```ts
import {HL7_2_2} from "node-hl7-client/lib/types/hl7";
```

**Comment by Bugs5382** [comment]
I am looking for an NPM package that does this type of "sub" package as a typescript. Not sure the above is the best method.

**Comment by glenarama** [comment]
That didn't help, could you not just export them at the top level? They would get shaken out when not used.

**Comment by Bugs5382** [comment]
Yeah. I just ran a test on one of the apps I am doing.. which I am using 2.7 ... so ok. Let me re-work this tonight. :)

**Comment by Bugs5382** [comment]
So, going over the code, I can't merge it into the main thing; otherwise, things will break. Yikes. So, I gotta figure out this sub-module issue.

**Comment by Bugs5382** [comment]
Ok. I got it working in my code now.... 

import {HL7_2_3} from "node-hl7-client/hl7"; now will work in upcoming develop channel.

**Comment by Bugs5382** [comment]
#85 is being merged into develop now

**Comment by Bugs5382** [comment]
2.1.0-beta.3 is out. Please try it there...

```ts
import {HL7_2_2} from "node-hl7-client/hl7"
console.log(new HL7_2_2())
```

**Comment by glenarama** [comment]
Looks good! Thanks.

**Comment by Bugs5382** [comment]
@glenarama  - let me know so I can push it out to main. :)

**Comment by glenarama** [comment]
> @glenarama - let me know so I can push it out to main. :)

Its working good for me now thanks.
