### ISSUE TITLE
fix: parsing fails if message ends with line break

### ISSUE THREAD

**Issue by jtarvainen** [Bugs5382/node-hl7-client#96]
If the inbound message ends with a line break ('\n', '\r', '\r\n'), message parsing fails with a `HL7FatalError` ("Segment must have a name."). This is especially problematic since the original message is stored as a private variable in the response, which also causes `res.sendResponse('AA')` to fail if the original message contains a trailing line break.

For example, this message cannot be parsed:

```
new Message({ text: 'MSH|^~\\&|device||Host||20240101000000+0000||OUL^R22^OUL_R22|2|P|2.5.1|||NE|AL||UNICODE UTF-8|||LAB-01^IHE\r' });
```

But this can:

```
new Message({ text: 'MSH|^~\\&|device||Host||20240101000000+0000||OUL^R22^OUL_R22|2|P|2.5.1|||NE|AL||UNICODE UTF-8|||LAB-01^IHE' });
```

I would suggest that the inbound message string be automatically trimmed (`String.prototype.trim()`) upon reception (i.e. before it's set in `req._message` and `res._message`) to remove any trailing line breaks.

Also, it'd be great if the library would log the error in the `res.sendResponse()` catch block before sending an "AE" message (the "AA" message creation failure is currently silent).

Thanks!

**Comment by Bugs5382** [comment]
@jtarvainen So I moved it here cause the server doesn't do the parsing anyway. This is just a result of the node-hl7 client not doing it correctly and now corrected in #97 

https://github.com/Bugs5382/node-hl7-client/blob/adb09115964b7857e33c6b11b1db84bc92beeefe/src/utils/normalizedBuilder.ts#L144

And the unit test:

https://github.com/Bugs5382/node-hl7-client/blob/adb09115964b7857e33c6b11b1db84bc92beeefe/__tests__/hl7.sanity.test.ts#L224

and

https://github.com/Bugs5382/node-hl7-client/blob/adb09115964b7857e33c6b11b1db84bc92beeefe/__tests__/hl7.sanity.test.ts#L226-L231

All pass, @jtarvainen

**Comment by jtarvainen** [comment]
Looks good to me!

**Comment by Bugs5382** [comment]
@jtarvainen This package has been released! Be sure to leave me a star!
